"""Validate and propagate the canonical Table S7(C) and S7(D) results.

The canonical numerical analyses are generated by
``notebooks/11_physics_aware_R_descriptor.ipynb``.  This script deliberately
does not refit or redefine either analysis.  It checks those outputs against
the current processed dataset and then refreshes the Figure 4 and Supporting
Information CSVs that historically retained stale, hard-coded values.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DATA_PATH = PROJECT_ROOT / "data" / "processed" / "hydrovoltaic_dataset_phase2_input_utf8.csv"
RESULTS_DIR = PROJECT_ROOT / "results"
FIG4_DIR = RESULTS_DIR / "figure4_resistance_regimes"
TABLE_DIR = RESULTS_DIR / "supporting_materials" / "tables"

S7C_CANONICAL_PATH = RESULTS_DIR / "11_R_regime_performance_statistics.csv"
S7D_CANONICAL_PATH = RESULTS_DIR / "11_physics_R_descriptor_model_comparison.csv"

TARGET = "log_estimated_power_density"
R_COLUMN = "log_internal_resistance_Mohm"
R_THRESHOLD = -1.0
EXPECTED_N = 112
EXPECTED_MISSING_R = 47
REGIME_ORDER = ["low_R", "high_R"]
MODEL_ORDER = ["baseline_logR", "centered_logR", "R_regime_descriptor"]
MODEL_LABELS = {
    "baseline_logR": "Raw log(R)",
    "centered_logR": "Centered log(R)",
    "R_regime_descriptor": "R-regime descriptor",
}
THRESHOLD_NOTE = "log(R) = -1; low_R if log(R) <= -1, high_R if log(R) > -1"


def calculate_s7c_from_data() -> pd.DataFrame:
    """Freshly calculate S7(C) from observed R values only."""
    df = pd.read_csv(DATA_PATH, encoding="utf-8-sig")
    log_r = pd.to_numeric(df[R_COLUMN], errors="coerce")
    target = pd.to_numeric(df[TARGET], errors="coerce")

    if int(log_r.isna().sum()) != EXPECTED_MISSING_R:
        raise AssertionError(
            f"Expected {EXPECTED_MISSING_R} missing-R records; found {log_r.isna().sum()}."
        )

    observed = pd.DataFrame({"log_R": log_r, "log_P_est": target}).dropna(
        subset=["log_R", "log_P_est"]
    )
    if len(observed) != EXPECTED_N:
        raise AssertionError(f"Expected {EXPECTED_N} observed-R records; found {len(observed)}.")

    observed["R_regime"] = np.where(
        observed["log_R"] <= R_THRESHOLD,
        "low_R",
        "high_R",
    )

    summary = (
        observed.groupby("R_regime")
        .agg(
            count=("log_P_est", "count"),
            mean_log_P_est=("log_P_est", "mean"),
            median_log_P_est=("log_P_est", "median"),
            std_log_P_est=("log_P_est", "std"),
            mean_log_R=("log_R", "mean"),
            median_log_R=("log_R", "median"),
        )
        .reindex(REGIME_ORDER)
        .reset_index()
    )
    summary.insert(1, "threshold", THRESHOLD_NOTE)

    if int(summary["count"].sum()) != EXPECTED_N:
        raise AssertionError("S7(C) group counts do not sum to 112.")
    return summary


def validate_s7c() -> pd.DataFrame:
    """Verify the Notebook 11 S7(C) result against a fresh calculation."""
    fresh = calculate_s7c_from_data()
    canonical = pd.read_csv(S7C_CANONICAL_PATH, encoding="utf-8-sig")
    canonical = canonical[fresh.columns].copy()
    canonical["R_regime"] = pd.Categorical(
        canonical["R_regime"], categories=REGIME_ORDER, ordered=True
    )
    canonical = canonical.sort_values("R_regime").reset_index(drop=True)
    canonical["R_regime"] = canonical["R_regime"].astype(str)

    pd.testing.assert_frame_equal(
        canonical,
        fresh,
        check_exact=False,
        rtol=1e-12,
        atol=1e-12,
        check_dtype=False,
    )
    return fresh


def validate_and_format_s7d() -> pd.DataFrame:
    """Validate the corrected Notebook 11 comparison and format the SI panel."""
    canonical = pd.read_csv(S7D_CANONICAL_PATH, encoding="utf-8-sig")
    required = {
        "model",
        "n_samples",
        "cv_R2_mean",
        "cv_R2_std",
        "test_R2",
    }
    missing = required.difference(canonical.columns)
    if missing:
        raise AssertionError(f"S7(D) canonical output is missing columns: {sorted(missing)}")

    selected = canonical.set_index("model").reindex(MODEL_ORDER)
    if selected.index.hasnans or selected["cv_R2_mean"].isna().any():
        raise AssertionError("S7(D) canonical output does not contain all three formulations.")
    if not (selected["n_samples"] == EXPECTED_N).all():
        raise AssertionError("Every S7(D) formulation must use n=112.")

    output = selected.reset_index().rename(columns={"model": "descriptor_model"})
    output.insert(1, "label", output["descriptor_model"].map(MODEL_LABELS))
    return output[
        [
            "descriptor_model",
            "label",
            "n_samples",
            "cv_R2_mean",
            "cv_R2_std",
            "test_R2",
        ]
    ]


def write_outputs(s7c: pd.DataFrame, s7d: pd.DataFrame) -> None:
    """Refresh only the production CSVs derived from S7(C) and S7(D)."""
    FIG4_DIR.mkdir(parents=True, exist_ok=True)
    TABLE_DIR.mkdir(parents=True, exist_ok=True)

    fig4b = s7c.drop(columns="threshold")
    fig4b.to_csv(
        FIG4_DIR / "fig4B_R_regime_summary.csv",
        index=False,
        encoding="utf-8-sig",
    )

    for name in (
        "fig4D_R_descriptor_comparison.csv",
        "fig4D_physics_aware_R_descriptor_comparison.csv",
    ):
        s7d.to_csv(FIG4_DIR / name, index=False, encoding="utf-8-sig")

    s7c.to_csv(
        TABLE_DIR / "Table_S7C_resistance_regime_performance_statistics.csv",
        index=False,
        encoding="utf-8-sig",
    )
    s7d.to_csv(
        TABLE_DIR / "Table_S7D_R_descriptor_comparison.csv",
        index=False,
        encoding="utf-8-sig",
    )


def main() -> None:
    s7c = validate_s7c()
    s7d = validate_and_format_s7d()
    write_outputs(s7c, s7d)

    print("Validated and refreshed Table S7(C) and Table S7(D).")
    print(f"Observed-R n: {int(s7c['count'].sum())}")
    print("S7(C):")
    print(s7c.to_string(index=False))
    print("S7(D):")
    print(s7d.to_string(index=False))


if __name__ == "__main__":
    main()
